name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 14
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - run: npm install
    - run: npm run lint
    - run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}[
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHub-OIDC-docs-ui

    - name: Sync UI Bundle to S3
      # if the AWS_S3_BUCKET is undefined, the task will fail
      # also make sure that we are on master before publishing the "latest" version
      if: ${{ secrets.STATIC_CONTENT_BUCKET != '' && github.ref == 'refs/heads/master' }}
      run: |
        aws s3 sync --follow-symlinks --include '*.zip' --no-progress --region eu-west-1 build s3://${{ secrets.STATIC_CONTENT_BUCKET }}/build
